type Task {
    taskId: ID! @id
    title: String!
    description: String

    subIssues: [Task!]! @relationship(type: "DEPENDS_ON", direction: OUT, properties: "TaskProperties")
    assignees: [User!]! @relationship(type: "ASSIGNED_TO", direction: OUT, properties: "TaskAssigneeProperties")
}

input TaskInput {
    title: String!
    description: String
}

extend type Query {
    task(id: ID!): Task
}

extend type Mutation {
    createTask(task: TaskInput!): Task
    assignTask(taskId: ID, userId: ID): Boolean!
}

type TaskProperties @relationshipProperties {
    at: DateTime
}

type TaskAssigneeProperties @relationshipProperties {
    info: String
}