type Task {
    taskId: ID! @id
    title: String!
    description: String

    superIssues: [Task!]! @relationship(type: "HAS_PARENT", direction: OUT, properties: "TaskProperties")
    project: Project @relationship(type: "BELONGS_TO", direction: OUT)

    assignees: [User!]! @relationship(type: "ASSIGNED_TO", direction: OUT, properties: "TaskAssigneeProperties")
}

input TaskInput {
    title: String!
    description: String
}

extend type Query {
    task(id: ID!): Task
}

extend type Mutation {
    createTask(task: TaskInput!, projectId: ID!): Task!
    updateTask(taskId: ID!, task: TaskInput!): Task!
    assignTask(taskId: ID!, userId: ID!): Boolean!
    unassignTask(taskId: ID!, userId: ID!): Boolean!
    createSubTask(parentTaskId: ID!, task: TaskInput!, projectId: ID!): Task!
    attachSubTask(parentTaskId: ID!, childTaskId: ID!): Boolean!
    detachSubTask(parentTaskId: ID!, childTaskId: ID!): Boolean!
    deleteTask(taskId: ID!): Boolean!
}

type TaskProperties @relationshipProperties {
    info: String
}

type TaskAssigneeProperties @relationshipProperties {
    at: DateTime @timestamp(operations: [CREATE])
}